/** Handelsvertretervertrag nach HGB — Vorlage, vor Live-Einsatz anwaltlich prüfen. */

export type HvInput = {
  first: string;
  last: string;
  street: string;
  house: string;
  zip: string;
  city: string;
  email?: string;
  phone?: string;
  staffId?: string;
  birth?: string;
  taxId?: string;
  tradeNo?: string;
  start?: string;
  region?: string;
  stufe?: number;
  bands?: HvBand[];
};

export type HvBand = {
  provider: string;
  name: string;
  type: string;
  kwh_from: number;
  kwh_to: number;
  amount_eur: number;
  amount_ct_kwh: number;
};

export function formatHvBandLine(b: HvBand) {
  const from = Number(b.kwh_from).toLocaleString("de-DE");
  const to = Number(b.kwh_to) >= 999999 ? "offen" : Number(b.kwh_to).toLocaleString("de-DE");
  const euro = Number(b.amount_eur).toFixed(2).replace(".", ",");
  const extra = Number(b.amount_ct_kwh)
    ? ` + ${String(b.amount_ct_kwh).replace(".", ",")} ct/kWh`
    : "";
  return `${b.provider} · ${b.name} · ${b.type} · ${from}-${to} kWh · ${euro} EUR${extra}`;
}

export function fillHvAnlage1(bands: HvBand[] | undefined, stufe: number): string[] {
  const rows = (bands || []).filter((b) => Number.isFinite(Number(b.amount_eur)));
  const body = rows.length
    ? rows.map(formatHvBandLine)
    : ["[Provisionsliste Stufe 1 wird beim Erzeugen aus dem Portal übernommen]"];
  return [
    "ANLAGE 1 — PROVISIONSORDNUNG STUFE 1 (Stand Vertragsbeginn)",
    "",
    "Gültig ab Vertragsbeginn. Beträge netto, zzgl. gesetzlicher USt., soweit anfallend.",
    `Dieser Vertrag startet in Stufe ${stufe}. Nur die nachstehenden Stufe-1-Sätze gelten.`,
    "Stufe 2 und 3 gelten erst nach unterzeichneter Zusatzvereinbarung oder Freischaltung durch die GF.",
    "Keine Strukturprovision in Stufe 1.",
    "Fällig nach Bestätigung und Ablauf der 14-tägigen Kunden-Widerrufsfrist.",
    "Storno innerhalb 14 Tagen: voller Wegfall. Danach keine Rückrechnung außer bei Pflichtverletzung.",
    "",
    `Anzahl Positionen Stufe 1: ${rows.length}`,
    "Format: Anbieter · Tarif · Sparte · Verbrauch · Abschlussprovision",
    "",
    ...body,
  ];
}

export function dash(v?: string | null, fallback = "[Platzhalter]") {
  const s = (v ?? "").trim();
  return s || fallback;
}

export function fillHvVertrag(d: HvInput): string[] {
  const name = `${dash(d.first, "[Vorname]")} ${dash(d.last, "[Nachname]")}`.trim();
  const addr = `${dash(d.street, "[Straße]")} ${dash(d.house, "[Nr.]")}, ${dash(d.zip, "[PLZ]")} ${dash(d.city, "[Ort]")}`;
  const start = dash(d.start, "dem Tag der beiderseitigen Unterschrift");
  const stufe = Math.min(3, Math.max(1, Number(d.stufe) || 1));
  const staff = dash(d.staffId, "wird bei Anlage im Portal gesetzt");
  const region = dash(d.region, "das vom Unternehmer zugewiesene Gebiet");

  return [
    "E1 DIREKTVERTRIEB",
    "Energie, die zu Ihnen passt.",
    "",
    "HANDELSVERTRETERVERTRAG",
    "mit Provisionsordnung, AGB und Datenschutzhinweis",
    "nach deutschem Recht (§§ 84 ff. HGB, BGB)",
    "",
    "Rechtlicher Hinweis: Dies ist eine vollständige Arbeitsvorlage für selbstständige",
    "Handelsvertreter. Sie ersetzt keine anwaltliche Beratung. Vor der ersten Verwendung",
    "kurz von einem Anwalt (Arbeits-/Handelsrecht) gegenlesen lassen. Kein Arbeitsvertrag.",
    "",
    "§ 1 Vertragsparteien",
    "",
    "Unternehmer:",
    "E1 Direktvertrieb",
    "Inhaber: Orhan Salo und Luca-Marco Marrancone",
    "(nachfolgend gemeinsam „Unternehmer“ / „E1“)",
    "E-Mail: business@e1direktvertrieb.de    info@e1direktvertrieb.de",
    "Anschrift: [Straße, PLZ, Ort — Platzhalter bis endgültige Geschäftsadresse]",
    "USt-IdNr. / Steuernummer: [Platzhalter]    Register: [falls später GmbH: HRB-Platzhalter]",
    "",
    "Handelsvertreterin / Handelsvertreter:",
    `Name: ${name}`,
    `Anschrift: ${addr}`,
    `Mitarbeiter-ID im Portal: ${staff}`,
    `Telefon: ${dash(d.phone)}    E-Mail: ${dash(d.email)}`,
    `Geburtsdatum: ${dash(d.birth)}`,
    `Steuerliche Identifikationsnr. / USt-IdNr.: ${dash(d.taxId)}`,
    `Gewerbeanmeldung / Handelsregisternr.: ${dash(d.tradeNo)}`,
    "(nachfolgend „Handelsvertreter“)",
    "",
    "§ 2 Rechtsverhältnis — selbstständig, kein Arbeitsverhältnis",
    "",
    "(1) Der Handelsvertreter wird als selbstständiger Handelsvertreter im Sinne des",
    "§ 84 Abs. 1 HGB für E1 tätig. Er ist Kaufmann / Gewerbetreibender auf eigene",
    "Rechnung und Gefahr, nicht Arbeitnehmer, nicht sozialversicherungspflichtig über E1.",
    "",
    "(2) Der Handelsvertreter entscheidet frei über Arbeitszeit, Tourenplanung und",
    "persönlichen Einsatz, soweit die berechtigten Interessen von E1 (Gebiet, Qualität,",
    "Markenauftritt, gesetzliche Vorgaben) gewahrt bleiben. Es besteht kein Direktionsrecht",
    "im arbeitsrechtlichen Sinn.",
    "",
    "(3) Der Handelsvertreter führt ein Gewerbe, führt Steuern und Sozialversicherung",
    "selbst ab, stellt auf Verlangen eine ordnungsgemäße Rechnung und führt, soweit",
    "umsatzsteuerpflichtig, die Umsatzsteuer selbst ab. E1 zahlt keine Lohnsteuer ab.",
    "",
    "(4) Beide Seiten wollen keine Scheinselbstständigkeit. Der Handelsvertreter",
    "versichert, auch für andere Auftraggeber tätig werden zu dürfen, soweit § 10",
    "(Vertraulichkeit und Konkurrenz während der Vertragslaufzeit) eingehalten wird.",
    "",
    "§ 3 Beginn, Gebiet, Portal",
    "",
    `(1) Der Vertrag beginnt am ${start} und läuft auf unbestimmte Zeit.`,
    `(2) Tätigkeitsgebiet: ${region}. Das Gebiet kann E1 im Portal zuweisen und ändern.`,
    "(3) Der Handelsvertreter erhält Zugang zum E1-Portal (Mitarbeiter-ID, Authenticator).",
    "Abschlüsse, Leads, Touren und Provisionen werden dort dokumentiert.",
    "",
    "§ 4 Aufgaben des Handelsvertreters",
    "",
    "(1) Vermittlung von Energieverträgen (Strom/Gas) und verwandten Produkten von E1",
    "bzw. der von E1 benannten Lieferanten (derzeit über New Sales, später eigene Tarife).",
    "(2) Sorgfältige, wahrheitsgemäße Beratung nach EnWG, UWG, PAngV und den Schulungen von E1.",
    "(3) Keine irreführenden Angaben zu Preisen, Laufzeit, Widerruf oder Identität des Lieferanten.",
    "(4) Kundendaten nur im Portal / auf den von E1 vorgegebenen Formularen; DSGVO einhalten.",
    "(5) Nicht angetroffene Haushalte und Hinweise im Portal erfassen, soweit vorgesehen.",
    "(6) Unterlagen, Ausweise und Werbeaussagen nur in der von E1 freigegebenen Fassung.",
    "",
    "§ 5 Pflichten von E1",
    "",
    "(1) E1 stellt Schulung, Produktinformationen, Portal, Gebietshinweise und Werbemittel.",
    "(2) E1 rechnet Provisionen nach diesem Vertrag und der Provisionsordnung ab.",
    "(3) E1 informiert über wesentliche Produkt- oder Prozessänderungen.",
    "",
    "§ 6 Provisionserklärung",
    "",
    "(1) Der Handelsvertreter erhält für jeden von ihm nachweislich vermittelten und",
    "wirksam zustande gekommenen Vertrag eine Abschlussprovision nach der jeweils",
    "geltenden Provisionsordnung (Anlage 1) und der ihm zugeordneten Stufe.",
    "",
    `(2) Zu Beginn gilt ausschließlich Stufe ${stufe}. Eine höhere Stufe entsteht nicht`,
    "automatisch, nicht durch Zeitablauf und nicht durch bloße mündliche Zusage.",
    "",
    "(3) Fällig wird die Provision, sobald der vermittelte Vertrag im Portal den Status",
    "„bestätigt“ (oder einen gleichwertigen Status) hat und die Widerrufsfrist des Kunden",
    "abgelaufen ist. Auszahlung nach der im Portal festgelegten Abrechnungsperiode,",
    "auf das vom Handelsvertreter benannte Konto, ggf. gegen Rechnung.",
    "",
    "(4) Folge- und Bestandsprovisionen nur, wenn die Provisionsordnung sie für die",
    "jeweilige Stufe ausdrücklich vorsieht. Strukturprovision nur, wenn E1 sie für",
    "die Mitarbeiter-ID schriftlich / im Portal freischaltet.",
    "",
    "(5) Kosten der eigenen Tätigkeit (Fahrt, Telefon, Arbeitsmittel) trägt der",
    "Handelsvertreter, soweit nicht schriftlich etwas anderes vereinbart ist.",
    "",
    "§ 7 Stufen — nur durch Zusatzvereinbarung",
    "",
    "(1) Es gibt die Stufen 1, 2 und 3. Sie beschreiben ausschließlich die Höhe und",
    "Staffelung der Provision (Anlage 1). Sie begründen kein Arbeitsverhältnis und",
    "keine Beförderung im hierarchischen Sinn.",
    "",
    `(2) Der Handelsvertreter startet in Stufe ${stufe}.`,
    "",
    "(3) Eine Höherstufung (z. B. von Stufe 1 auf Stufe 2) erfolgt nur durch eine",
    "gesonderte, von beiden Seiten unterzeichnete Zusatzvereinbarung (Muster Anlage 4)",
    "oder durch ausdrückliche Freischaltung der Stufe im Portal durch die Geschäftsführung",
    "(Orhan Salo / Luca-Marco Marrancone). Ohne diese Form bleibt Stufe 1 maßgeblich.",
    "",
    "(4) E1 entscheidet frei, ob und wann eine Höherstufung angeboten wird. Ein",
    "Anspruch auf Höherstufung besteht nicht.",
    "",
    "§ 8 Storno und Widerruf des Kunden",
    "",
    "(1) Endkunden haben ein gesetzliches Widerrufsrecht von 14 Tagen.",
    "(2) Widerruft oder storniert der Kunde innerhalb von 14 Tagen nach Abschluss,",
    "entfällt der Provisionsanspruch. Bereits ausgezahlte Beträge sind in dieser Frist",
    "zurückzugewähren bzw. werden verrechnet.",
    "(3) Nach Ablauf der 14 Tage findet keine Provisionsrückrechnung mehr statt,",
    "es sei denn, der Handelsvertreter hat den Abschluss durch Täuschung, Drohung",
    "oder grobe Pflichtverletzung herbeigeführt; dann bleiben gesetzliche Ansprüche unberührt.",
    "",
    "§ 9 Abrechnung, Einblick, Einbehalte",
    "",
    "(1) Abrechnung über das Portal. Der Handelsvertreter prüft sie unverzüglich.",
    "Einwendungen binnen 14 Tagen, sonst gilt die Abrechnung als genehmigt.",
    "(2) E1 darf offene Rückforderungsansprüche mit fälligen Provisionen verrechnen.",
    "",
    "§ 10 Vertraulichkeit, Daten, Wettbewerb während der Laufzeit",
    "",
    "(1) Kundendaten, Gebietsdaten, Provisionsregeln und Geschäftsgeheimnisse von E1",
    "sind vertraulich, auch nach Vertragsende, solange sie geheim sind.",
    "(2) Personenbezogene Daten nur zur Vertragserfüllung, nach Weisung von E1 als",
    "Auftragsverarbeiter im Sinne der DSGVO, soweit E1 Verantwortlicher ist.",
    "(3) Während der Vertragslaufzeit keine Vermittlung gleicher Energieprodukte für",
    "unmittelbare Wettbewerber im zugewiesenen Gebiet, es sei denn E1 stimmt schriftlich zu.",
    "Ein nachvertragliches Wettbewerbsverbot wird nicht vereinbart (Schutz des § 90a HGB:",
    "nur mit Karenzentschädigung; hier bewusst nicht vereinbart).",
    "",
    "§ 11 Dauer und Kündigung (§ 89 HGB)",
    "",
    "(1) Jede Seite kann mit der gesetzlichen Frist des § 89 HGB kündigen:",
    "im ersten Jahr: ein Monat zum Monatsende;",
    "im zweiten Jahr: zwei Monate zum Monatsende;",
    "im dritten bis fünften Jahr: drei Monate zum Monatsende;",
    "danach: sechs Monate zum Monatsende.",
    "Längere Fristen können schriftlich vereinbart werden, kürzere nur, soweit das Gesetz es zulässt.",
    "(2) Fristlose Kündigung aus wichtigem Grund (§ 89a HGB) bleibt unberührt",
    "(z. B. grobe Falschberatung, Datenmissbrauch, Straftaten im Zusammenhang mit der Tätigkeit).",
    "(3) Kündigung schriftlich (Textform E-Mail an business@e1direktvertrieb.de genügt).",
    "",
    "§ 12 Ausgleichsanspruch (§ 89b HGB)",
    "",
    "Ein möglicher Ausgleichsanspruch nach § 89b HGB bleibt nach den gesetzlichen",
    "Voraussetzungen unberührt. Ein Vorausverzicht ist unwirksam. Über Höhe und",
    "Berechnung wird im Beendigungsfall gesondert gesprochen.",
    "",
    "§ 13 Haftung, Qualität",
    "",
    "(1) Jede Seite haftet für Vorsatz und grobe Fahrlässigkeit unbeschränkt, für",
    "einfache Fahrlässigkeit nur bei Verletzung wesentlicher Vertragspflichten und",
    "begrenzt auf den vorhersehbaren Schaden, außer bei Leben, Körper, Gesundheit",
    "oder zwingenden gesetzlichen Haftungstatbeständen.",
    "(2) Wiederholte Qualitätsmängel (hohe Stornoquote durch Fehlberatung, Beschwerden)",
    "können Abmahnung, Gebietssperre im Portal oder Kündigung rechtfertigen.",
    "(3) E1 haftet nicht für den wirtschaftlichen Erfolg des Handelsvertreters",
    "(kein Mindestverdienst, keine Erfolgsgarantie).",
    "",
    "§ 14 Vertragsstrafen (Absicherung E1)",
    "",
    "(1) Der Handelsvertreter ist Kaufmann. Für die nachstehenden Vertragsstrafen gilt",
    "§ 348 HGB (keine Herabsetzung nach § 343 BGB), soweit gesetzlich zulässig.",
    "Die Strafe ist sofort fällig, wenn der Verstoß dem Handelsvertreter zuzurechnen ist.",
    "E1 kann zusätzlich Unterlassung, Auskunft, Schadensersatz und Kündigung verlangen.",
    "Gezahlte Strafe wird auf einen weitergehenden Schadensersatz angerechnet.",
    "",
    "(2) Für jeden Fall der Zuwiderhandlung gilt, bei Dauerverstoß je angefangene Woche:",
    "",
    "a) Verstoß gegen Vertraulichkeit, Mitnahme oder Nutzung von Kunden-, Gebiets- oder",
    "Provisionsdaten nach Vertragsende oder für eigene/fremde Zwecke: 5.000 EUR.",
    "b) Vermittlung gleicher Energieprodukte für einen unmittelbaren Wettbewerber im",
    "zugewiesenen Gebiet während der Vertragslaufzeit ohne Zustimmung: 5.000 EUR je Fall.",
    "c) Abwerben von E1-Kunden oder E1-Handelsvertretern während der Laufzeit für einen",
    "Wettbewerber: 2.500 EUR je Person / je Vertrag.",
    "d) Vorsätzliche oder grob fahrlässige Falschberatung, Identitätstäuschung",
    "(Auftreten als Stadtwerke, Netzbetreiber, Behörde) oder Unterschlagen der",
    "gesetzlichen Widerrufsbelehrung: 5.000 EUR je Fall.",
    "e) Entgegennahme von Kundengeldern, fremden PINs, vollständigen Kartendaten oder",
    "nicht vorgesehenen Vollmachten: 5.000 EUR je Fall.",
    "f) Weitergabe von Portal-Zugang, Authenticator-Key oder Unterschriftenmappe an",
    "Dritte: 3.000 EUR je Fall.",
    "g) Unerlaubte Untervertretung oder Einsatz nicht gemeldeter Hilfskräfte gegenüber",
    "Kunden im Namen E1: 2.500 EUR je Fall.",
    "h) Öffentliche herabsetzende Äußerungen über E1, die Inhaber oder Produkte, die",
    "geeignet sind, den Ruf erheblich zu schädigen: 2.500 EUR je Fall.",
    "",
    "(3) Die Geltendmachung mehrerer Straftatbestände aus einem Lebenssachverhalt ist",
    "zulässig, insgesamt jedoch der Höhe nach auf 25.000 EUR je Lebenssachverhalt",
    "begrenzt, unbeschadet eines höheren nachweisbaren Schadens.",
    "(4) Die Strafe entfällt, wenn der Handelsvertreter nachweist, dass ihn kein",
    "Verschulden trifft.",
    "",
    "§ 15 Freistellung, Regress, Behörden",
    "",
    "(1) Der Handelsvertreter stellt E1, die Inhaber Orhan Salo und Luca-Marco Marrancone",
    "sowie Erfüllungsgehilfen von allen Ansprüchen Dritter frei, die auf einer",
    "Pflichtverletzung des Handelsvertreters beruhen (insbesondere UWG, EnWG, DSGVO,",
    "Betrugsvorwurf, Falschberatung, unzulässige Haustürwerbung). Das umfasst",
    "berechtigte Vergleichszahlungen, Anwalts- und Gerichtskosten.",
    "(2) E1 darf solche Forderungen mit Provisionsansprüchen verrechnen.",
    "(3) Der Handelsvertreter wirkt bei Behörden-, Netz- und Lieferantenanfragen unverzüglich",
    "mit und legt auf Verlangen Touren- und Beratungsdokumentation vor.",
    "",
    "§ 16 Keine Vollmacht, verbotene Handlungen",
    "",
    "(1) Der Handelsvertreter hat keine Vollmacht, E1 zu verpflichten außer zur",
    "Entgegennahme von Vertragsanträgen auf den E1-Formularen / im Portal.",
    "(2) Ausdrücklich untersagt: eigene Preis- oder Bonusversprechen; Änderung von AGB",
    "oder Widerrufsbelehrung; Inkasso; Schuldanerkenntnisse; Kreditgeschäfte im Namen E1;",
    "Nutzung der Marke E1 außerhalb freigegebener Werbemittel; Domain- oder Profilanlage",
    "mit „E1“ ohne Zustimmung.",
    "(3) Mündliche Zusagen des Handelsvertreters gegenüber Kunden binden E1 nicht.",
    "",
    "§ 17 Versicherung, Nachweise, Compliance",
    "",
    "(1) Der Handelsvertreter hält auf eigene Kosten eine Berufshaftpflicht in angemessener",
    "Höhe vor (empfohlen mindestens 1.000.000 EUR für Personen- und Vermögensschäden)",
    "und weist sie E1 auf Anforderung nach.",
    "(2) Vor Aufnahme der Tätigkeit legt er vor: Gewerbeanmeldung, Ausweis, steuerliche",
    "Nummer, Bankverbindung, dieses Vertragsexemplar unterschrieben.",
    "(3) Er beachtet UWG, EnWG, DSGVO, TMG/DDG, PAngV und die Schulungsvorgaben von E1.",
    "Haustürgeschäfte nur unter Beachtung von Hausrecht und Widerrufsbelehrung.",
    "",
    "§ 18 Herausgabe, Zugangssperre, Beweissicherung",
    "",
    "(1) Bei Vertragsende, Sperre oder auf erstes Anfordern gibt der Handelsvertreter",
    "sämtliche Unterlagen, Kundendaten, Geräte und Werbemittel von E1 heraus und löscht",
    "Kopien, soweit keine gesetzliche Aufbewahrungspflicht entgegensteht. Zugang zum",
    "Portal darf E1 sofort sperren.",
    "(2) Provisionsansprüche sind ohne Zustimmung von E1 nicht abtretbar und nicht",
    "verpfändbar. Aufrechnung durch den Handelsvertreter nur mit unbestrittenen oder",
    "rechtskräftig festgestellten Forderungen.",
    "(3) E1 darf Pflichtverstöße dokumentieren (Portal-Logs, Beschwerden) und im Streitfall",
    "verwenden, soweit datenschutzrechtlich zulässig.",
    "",
    "§ 19 Schlussbestimmungen",
    "",
    "(1) Es gilt deutsches Recht. UN-Kaufrecht ist ausgeschlossen.",
    "(2) Gerichtsstand, soweit gesetzlich zulässig, ist der Sitz von E1; E1 darf auch",
    "am Sitz des Handelsvertreters klagen.",
    "(3) Änderungen, auch der Stufe, bedürfen der Textform. Mündliche Nebenabreden",
    "bestehen nicht. Anlage 1 bis 4 sind Bestandteil dieses Vertrags.",
    "(4) Sollte eine Klausel unwirksam sein, bleibt der Rest wirksam. An ihre Stelle",
    "tritt die gesetzliche Regelung, hilfsweise eine wirksame Klausel, die dem",
    "wirtschaftlichen Zweck am nächsten kommt.",
    "(5) Der Handelsvertreter hat die Anlagen gelesen, die Vertragsstrafen zur Kenntnis",
    "genommen und bestätigt den Empfang je eines Exemplars.",
    "",
    "Ort, Datum: ____________________________",
    "",
    `Handelsvertreter: ${name}`,
    "Unterschrift: ____________________________   /sign1/",
    "",
    "E1 Direktvertrieb, Inhaber Orhan Salo und Luca-Marco Marrancone",
    "Unterschrift Orhan Salo: ____________________________",
    "Unterschrift Luca-Marco Marrancone: ____________________________",
    "",
    "— Ende Hauptvertrag —",
    "",
    ...fillHvAnlage1(d.bands, stufe),
    "",
    "Stufe 2 und Stufe 3: nicht Gegenstand dieses Anfangsvertrags. Nur Anlage 4.",
    "",
    "ANLAGE 2 — AGB HANDELSVERTRETER (E1 DIREKTVERTRIEB)",
    "",
    "1. Geltung. Diese AGB gelten für die selbstständige Vertriebstätigkeit für E1.",
    "Verbraucher-AGB der Endkundenverträge bleiben unberührt.",
    "2. Auftreten. Der Handelsvertreter tritt im Namen und für Rechnung der Vermittlung",
    "von E1 auf, nicht als Lieferant, sofern E1 nicht ausdrücklich Lieferant ist.",
    "Visitenkarten und Kleidung nur in freigegebener Form. Keine eigenen Preisversprechen.",
    "3. Portal. Zugangsdaten sind persönlich. Authenticator-Key nicht weitergeben.",
    "4. Werbung. Keine Spam-Anrufe, keine unzulässige Haustürwerbung entgegen Hausrecht,",
    "kein Social-Media-Auftritt im Namen E1 ohne Freigabe.",
    "5. Unterlagen. Kundenformulare, Ausweise und Verträge bleiben Eigentum von E1 bzw.",
    "des Lieferanten und sind auf Verlangen herauszugeben.",
    "6. Zahlungen von Kunden. Der Handelsvertreter nimmt kein Bargeld und keine",
    "fremden IBAN-Vollmachten entgegen, außer SEPA im vorgesehenen Formular.",
    "7. Haftung für Hilfspersonen. Setzt der Handelsvertreter eigene Hilfskräfte ein,",
    "haftet er für diese. Untervertreter nur mit schriftlicher Zustimmung von E1.",
    "8. Aufrechnung. Nur mit unbestrittenen oder rechtskräftig festgestellten Forderungen.",
    "9. Abtretung. Provisionsansprüche nicht ohne Zustimmung von E1 abtretbar.",
    "10. Vertragsstrafe. Es gelten die Strafen des Hauptvertrags § 14; AGB wiederholen sie nicht.",
    "11. Marke. Kein Firmen-, Domain- oder Profilgebrauch „E1“ ohne Freigabe.",
    "12. Salvatorisch / Recht / Gerichtsstand. Wie Hauptvertrag.",
    "",
    "ANLAGE 3 — DATENSCHUTZ (HANDELSVERTRETER)",
    "",
    "Verantwortlicher für Mitarbeiterstammdaten: E1 Direktvertrieb, Inhaber Orhan Salo",
    "und Luca-Marco Marrancone, business@e1direktvertrieb.de.",
    "Zwecke: Vertragsdurchführung, Provision, Gebiet, Qualität, gesetzliche Pflichten.",
    "Rechtsgrundlage: Art. 6 Abs. 1 lit. b und f DSGVO, ggf. lit. c.",
    "Empfänger: Hosting (EU), Google Workspace für dienstliche E-Mail, Steuerberater,",
    "Behörden soweit Pflicht. Keine Drittlandübermittlung ohne Garantien.",
    "Speicherdauer: Vertragslaufzeit plus gesetzliche Aufbewahrung (i. d. R. 10 Jahre HGB/AO).",
    "Rechte: Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch, Beschwerde bei",
    "einer Aufsichtsbehörde. Kundendaten darf der Handelsvertreter nach Ende nicht behalten.",
    "",
    "ANLAGE 4 — MUSTER ZUSATZVEREINBARUNG STUFE",
    "",
    "Zusatzvereinbarung zum Handelsvertretervertrag",
    `Handelsvertreter: ${name}    Mitarbeiter-ID: ${staff}`,
    "Unternehmer: E1 Direktvertrieb, Inhaber Orhan Salo und Luca-Marco Marrancone",
    "",
    "Die Parteien vereinbaren, dass ab dem ______________ die Provisionsstufe",
    "______ (2 oder 3) gilt. Anlage 1 des Hauptvertrags gilt in der dann aktuellen",
    "Fassung des Portals. Alle übrigen Regelungen des Hauptvertrags bleiben unverändert.",
    "Ein Anspruch auf weitere Höherstufung entsteht nicht.",
    "",
    "Ort, Datum: ______________",
    "Handelsvertreter: ______________",
    "E1 Orhan Salo: ______________     E1 Luca-Marco Marrancone: ______________",
  ];
}
