/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AppRouteImport } from './routes/app'
import { Route as BeratungRouteImport } from './routes/beratung'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as EnergieRouteImport } from './routes/energie'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as KundeRouteImport } from './routes/kunde'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as VorschauRouteImport } from './routes/vorschau'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppKarteRouteImport } from './routes/app/karte'
import { Route as AppListeRouteImport } from './routes/app/liste'
import { Route as AppMehrRouteImport } from './routes/app/mehr'
import { Route as AppSucheRouteImport } from './routes/app/suche'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalBenachrichtigungenRouteImport } from './routes/portal/benachrichtigungen'
import { Route as PortalPlanungRouteImport } from './routes/portal/planung'
import { Route as PortalProfilRouteImport } from './routes/portal/profil'
import { Route as PortalProvisionenRouteImport } from './routes/portal/provisionen'
import { Route as PortalSteuernRouteImport } from './routes/portal/steuern'
import { Route as PortalTeamRouteImport } from './routes/portal/team'
import { Route as PortalWissenRouteImport } from './routes/portal/wissen'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocusignConnectRouteImport } from './routes/api/docusign/connect'
import { Route as PortalAdminAuditRouteImport } from './routes/portal/admin/audit'
import { Route as PortalAdminBenutzerRouteImport } from './routes/portal/admin/benutzer'
import { Route as PortalAdminEinstellungenRouteImport } from './routes/portal/admin/einstellungen'
import { Route as PortalAdminGebieteRouteImport } from './routes/portal/admin/gebiete'
import { Route as PortalAdminLeadsRouteImport } from './routes/portal/admin/leads'
import { Route as PortalAdminMailRouteImport } from './routes/portal/admin/mail'
import { Route as PortalAdminOnboardingRouteImport } from './routes/portal/admin/onboarding'
import { Route as PortalAdminPartnerRouteImport } from './routes/portal/admin/partner'
import { Route as PortalAdminProdukteRouteImport } from './routes/portal/admin/produkte'
import { Route as PortalAdminQualitaetRouteImport } from './routes/portal/admin/qualitaet'
import { Route as PortalAdminRegionenRouteImport } from './routes/portal/admin/regionen'
import { Route as PortalAdminReportsRouteImport } from './routes/portal/admin/reports'
import { Route as PortalAdminSignaturRouteImport } from './routes/portal/admin/signatur'
import { Route as PortalAdminVertraegeRouteImport } from './routes/portal/admin/vertraege'
import { Route as PortalAuftraegeIndexRouteImport } from './routes/portal/auftraege/index'
import { Route as PortalAuftraegeIdRouteImport } from './routes/portal/auftraege/$id'
import { Route as PortalAuftraegeNeuRouteImport } from './routes/portal/auftraege/neu'
import { Route as PortalFeldIndexRouteImport } from './routes/portal/feld/index'
import { Route as PortalFeldWocheRouteImport } from './routes/portal/feld/woche'
import { Route as PortalKundenIndexRouteImport } from './routes/portal/kunden/index'
import { Route as PortalKundenIdRouteImport } from './routes/portal/kunden/$id'
import { Route as PortalPostfachIndexRouteImport } from './routes/portal/postfach/index'
import { Route as PortalPostfachIdRouteImport } from './routes/portal/postfach/$id'
import { Route as PortalPostfachNeuRouteImport } from './routes/portal/postfach/neu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BeratungRoute = BeratungRouteImport.update({
  id: '/beratung',
  path: '/beratung',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergieRoute = EnergieRouteImport.update({
  id: '/energie',
  path: '/energie',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const KundeRoute = KundeRouteImport.update({
  id: '/kunde',
  path: '/kunde',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const VorschauRoute = VorschauRouteImport.update({
  id: '/vorschau',
  path: '/vorschau',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppKarteRoute = AppKarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => AppRoute,
} as any)
const AppListeRoute = AppListeRouteImport.update({
  id: '/liste',
  path: '/liste',
  getParentRoute: () => AppRoute,
} as any)
const AppMehrRoute = AppMehrRouteImport.update({
  id: '/mehr',
  path: '/mehr',
  getParentRoute: () => AppRoute,
} as any)
const AppSucheRoute = AppSucheRouteImport.update({
  id: '/suche',
  path: '/suche',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBenachrichtigungenRoute =
  PortalBenachrichtigungenRouteImport.update({
    id: '/benachrichtigungen',
    path: '/benachrichtigungen',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPlanungRoute = PortalPlanungRouteImport.update({
  id: '/planung',
  path: '/planung',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfilRoute = PortalProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProvisionenRoute = PortalProvisionenRouteImport.update({
  id: '/provisionen',
  path: '/provisionen',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSteuernRoute = PortalSteuernRouteImport.update({
  id: '/steuern',
  path: '/steuern',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTeamRoute = PortalTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWissenRoute = PortalWissenRouteImport.update({
  id: '/wissen',
  path: '/wissen',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocusignConnectRoute = ApiDocusignConnectRouteImport.update({
  id: '/api/docusign/connect',
  path: '/api/docusign/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminAuditRoute = PortalAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminBenutzerRoute = PortalAdminBenutzerRouteImport.update({
  id: '/admin/benutzer',
  path: '/admin/benutzer',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminEinstellungenRoute =
  PortalAdminEinstellungenRouteImport.update({
    id: '/admin/einstellungen',
    path: '/admin/einstellungen',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAdminGebieteRoute = PortalAdminGebieteRouteImport.update({
  id: '/admin/gebiete',
  path: '/admin/gebiete',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminLeadsRoute = PortalAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminMailRoute = PortalAdminMailRouteImport.update({
  id: '/admin/mail',
  path: '/admin/mail',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminOnboardingRoute = PortalAdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminPartnerRoute = PortalAdminPartnerRouteImport.update({
  id: '/admin/partner',
  path: '/admin/partner',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminProdukteRoute = PortalAdminProdukteRouteImport.update({
  id: '/admin/produkte',
  path: '/admin/produkte',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminQualitaetRoute = PortalAdminQualitaetRouteImport.update({
  id: '/admin/qualitaet',
  path: '/admin/qualitaet',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRegionenRoute = PortalAdminRegionenRouteImport.update({
  id: '/admin/regionen',
  path: '/admin/regionen',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminReportsRoute = PortalAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminSignaturRoute = PortalAdminSignaturRouteImport.update({
  id: '/admin/signatur',
  path: '/admin/signatur',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminVertraegeRoute = PortalAdminVertraegeRouteImport.update({
  id: '/admin/vertraege',
  path: '/admin/vertraege',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuftraegeIndexRoute = PortalAuftraegeIndexRouteImport.update({
  id: '/auftraege/',
  path: '/auftraege/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuftraegeIdRoute = PortalAuftraegeIdRouteImport.update({
  id: '/auftraege/$id',
  path: '/auftraege/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuftraegeNeuRoute = PortalAuftraegeNeuRouteImport.update({
  id: '/auftraege/neu',
  path: '/auftraege/neu',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeldIndexRoute = PortalFeldIndexRouteImport.update({
  id: '/feld/',
  path: '/feld/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeldWocheRoute = PortalFeldWocheRouteImport.update({
  id: '/feld/woche',
  path: '/feld/woche',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKundenIndexRoute = PortalKundenIndexRouteImport.update({
  id: '/kunden/',
  path: '/kunden/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKundenIdRoute = PortalKundenIdRouteImport.update({
  id: '/kunden/$id',
  path: '/kunden/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostfachIndexRoute = PortalPostfachIndexRouteImport.update({
  id: '/postfach/',
  path: '/postfach/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostfachIdRoute = PortalPostfachIdRouteImport.update({
  id: '/postfach/$id',
  path: '/postfach/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPostfachNeuRoute = PortalPostfachNeuRouteImport.update({
  id: '/postfach/neu',
  path: '/postfach/neu',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/app': typeof AppRouteWithChildren
  '/beratung': typeof BeratungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/energie': typeof EnergieRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kunde': typeof KundeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/vorschau': typeof VorschauRoute
  '/app/karte': typeof AppKarteRoute
  '/app/liste': typeof AppListeRoute
  '/app/mehr': typeof AppMehrRoute
  '/app/suche': typeof AppSucheRoute
  '/portal/benachrichtigungen': typeof PortalBenachrichtigungenRoute
  '/portal/planung': typeof PortalPlanungRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/provisionen': typeof PortalProvisionenRoute
  '/portal/steuern': typeof PortalSteuernRoute
  '/portal/team': typeof PortalTeamRoute
  '/portal/wissen': typeof PortalWissenRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/docusign/connect': typeof ApiDocusignConnectRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/benutzer': typeof PortalAdminBenutzerRoute
  '/portal/admin/einstellungen': typeof PortalAdminEinstellungenRoute
  '/portal/admin/gebiete': typeof PortalAdminGebieteRoute
  '/portal/admin/leads': typeof PortalAdminLeadsRoute
  '/portal/admin/mail': typeof PortalAdminMailRoute
  '/portal/admin/onboarding': typeof PortalAdminOnboardingRoute
  '/portal/admin/partner': typeof PortalAdminPartnerRoute
  '/portal/admin/produkte': typeof PortalAdminProdukteRoute
  '/portal/admin/qualitaet': typeof PortalAdminQualitaetRoute
  '/portal/admin/regionen': typeof PortalAdminRegionenRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/signatur': typeof PortalAdminSignaturRoute
  '/portal/admin/vertraege': typeof PortalAdminVertraegeRoute
  '/portal/auftraege/$id': typeof PortalAuftraegeIdRoute
  '/portal/auftraege/neu': typeof PortalAuftraegeNeuRoute
  '/portal/feld/woche': typeof PortalFeldWocheRoute
  '/portal/kunden/$id': typeof PortalKundenIdRoute
  '/portal/postfach/$id': typeof PortalPostfachIdRoute
  '/portal/postfach/neu': typeof PortalPostfachNeuRoute
  '/portal/auftraege/': typeof PortalAuftraegeIndexRoute
  '/portal/feld/': typeof PortalFeldIndexRoute
  '/portal/kunden/': typeof PortalKundenIndexRoute
  '/portal/postfach/': typeof PortalPostfachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/beratung': typeof BeratungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/energie': typeof EnergieRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kunde': typeof KundeRoute
  '/login': typeof LoginRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vorschau': typeof VorschauRoute
  '/app/karte': typeof AppKarteRoute
  '/app/liste': typeof AppListeRoute
  '/app/mehr': typeof AppMehrRoute
  '/app/suche': typeof AppSucheRoute
  '/portal/benachrichtigungen': typeof PortalBenachrichtigungenRoute
  '/portal/planung': typeof PortalPlanungRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/provisionen': typeof PortalProvisionenRoute
  '/portal/steuern': typeof PortalSteuernRoute
  '/portal/team': typeof PortalTeamRoute
  '/portal/wissen': typeof PortalWissenRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/docusign/connect': typeof ApiDocusignConnectRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/benutzer': typeof PortalAdminBenutzerRoute
  '/portal/admin/einstellungen': typeof PortalAdminEinstellungenRoute
  '/portal/admin/gebiete': typeof PortalAdminGebieteRoute
  '/portal/admin/leads': typeof PortalAdminLeadsRoute
  '/portal/admin/mail': typeof PortalAdminMailRoute
  '/portal/admin/onboarding': typeof PortalAdminOnboardingRoute
  '/portal/admin/partner': typeof PortalAdminPartnerRoute
  '/portal/admin/produkte': typeof PortalAdminProdukteRoute
  '/portal/admin/qualitaet': typeof PortalAdminQualitaetRoute
  '/portal/admin/regionen': typeof PortalAdminRegionenRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/signatur': typeof PortalAdminSignaturRoute
  '/portal/admin/vertraege': typeof PortalAdminVertraegeRoute
  '/portal/auftraege/$id': typeof PortalAuftraegeIdRoute
  '/portal/auftraege/neu': typeof PortalAuftraegeNeuRoute
  '/portal/feld/woche': typeof PortalFeldWocheRoute
  '/portal/kunden/$id': typeof PortalKundenIdRoute
  '/portal/postfach/$id': typeof PortalPostfachIdRoute
  '/portal/postfach/neu': typeof PortalPostfachNeuRoute
  '/portal/auftraege': typeof PortalAuftraegeIndexRoute
  '/portal/feld': typeof PortalFeldIndexRoute
  '/portal/kunden': typeof PortalKundenIndexRoute
  '/portal/postfach': typeof PortalPostfachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/app': typeof AppRouteWithChildren
  '/beratung': typeof BeratungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/energie': typeof EnergieRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/kunde': typeof KundeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/vorschau': typeof VorschauRoute
  '/app/karte': typeof AppKarteRoute
  '/app/liste': typeof AppListeRoute
  '/app/mehr': typeof AppMehrRoute
  '/app/suche': typeof AppSucheRoute
  '/portal/benachrichtigungen': typeof PortalBenachrichtigungenRoute
  '/portal/planung': typeof PortalPlanungRoute
  '/portal/profil': typeof PortalProfilRoute
  '/portal/provisionen': typeof PortalProvisionenRoute
  '/portal/steuern': typeof PortalSteuernRoute
  '/portal/team': typeof PortalTeamRoute
  '/portal/wissen': typeof PortalWissenRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/docusign/connect': typeof ApiDocusignConnectRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/benutzer': typeof PortalAdminBenutzerRoute
  '/portal/admin/einstellungen': typeof PortalAdminEinstellungenRoute
  '/portal/admin/gebiete': typeof PortalAdminGebieteRoute
  '/portal/admin/leads': typeof PortalAdminLeadsRoute
  '/portal/admin/mail': typeof PortalAdminMailRoute
  '/portal/admin/onboarding': typeof PortalAdminOnboardingRoute
  '/portal/admin/partner': typeof PortalAdminPartnerRoute
  '/portal/admin/produkte': typeof PortalAdminProdukteRoute
  '/portal/admin/qualitaet': typeof PortalAdminQualitaetRoute
  '/portal/admin/regionen': typeof PortalAdminRegionenRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/signatur': typeof PortalAdminSignaturRoute
  '/portal/admin/vertraege': typeof PortalAdminVertraegeRoute
  '/portal/auftraege/$id': typeof PortalAuftraegeIdRoute
  '/portal/auftraege/neu': typeof PortalAuftraegeNeuRoute
  '/portal/feld/woche': typeof PortalFeldWocheRoute
  '/portal/kunden/$id': typeof PortalKundenIdRoute
  '/portal/postfach/$id': typeof PortalPostfachIdRoute
  '/portal/postfach/neu': typeof PortalPostfachNeuRoute
  '/portal/auftraege/': typeof PortalAuftraegeIndexRoute
  '/portal/feld/': typeof PortalFeldIndexRoute
  '/portal/kunden/': typeof PortalKundenIndexRoute
  '/portal/postfach/': typeof PortalPostfachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/app'
    | '/beratung'
    | '/datenschutz'
    | '/energie'
    | '/impressum'
    | '/karriere'
    | '/kunde'
    | '/login'
    | '/portal'
    | '/ueber-uns'
    | '/vorschau'
    | '/app/karte'
    | '/app/liste'
    | '/app/mehr'
    | '/app/suche'
    | '/portal/benachrichtigungen'
    | '/portal/planung'
    | '/portal/profil'
    | '/portal/provisionen'
    | '/portal/steuern'
    | '/portal/team'
    | '/portal/wissen'
    | '/app/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/docusign/connect'
    | '/portal/admin/audit'
    | '/portal/admin/benutzer'
    | '/portal/admin/einstellungen'
    | '/portal/admin/gebiete'
    | '/portal/admin/leads'
    | '/portal/admin/mail'
    | '/portal/admin/onboarding'
    | '/portal/admin/partner'
    | '/portal/admin/produkte'
    | '/portal/admin/qualitaet'
    | '/portal/admin/regionen'
    | '/portal/admin/reports'
    | '/portal/admin/signatur'
    | '/portal/admin/vertraege'
    | '/portal/auftraege/$id'
    | '/portal/auftraege/neu'
    | '/portal/feld/woche'
    | '/portal/kunden/$id'
    | '/portal/postfach/$id'
    | '/portal/postfach/neu'
    | '/portal/auftraege/'
    | '/portal/feld/'
    | '/portal/kunden/'
    | '/portal/postfach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/beratung'
    | '/datenschutz'
    | '/energie'
    | '/impressum'
    | '/karriere'
    | '/kunde'
    | '/login'
    | '/ueber-uns'
    | '/vorschau'
    | '/app/karte'
    | '/app/liste'
    | '/app/mehr'
    | '/app/suche'
    | '/portal/benachrichtigungen'
    | '/portal/planung'
    | '/portal/profil'
    | '/portal/provisionen'
    | '/portal/steuern'
    | '/portal/team'
    | '/portal/wissen'
    | '/app'
    | '/portal'
    | '/api/auth/$'
    | '/api/docusign/connect'
    | '/portal/admin/audit'
    | '/portal/admin/benutzer'
    | '/portal/admin/einstellungen'
    | '/portal/admin/gebiete'
    | '/portal/admin/leads'
    | '/portal/admin/mail'
    | '/portal/admin/onboarding'
    | '/portal/admin/partner'
    | '/portal/admin/produkte'
    | '/portal/admin/qualitaet'
    | '/portal/admin/regionen'
    | '/portal/admin/reports'
    | '/portal/admin/signatur'
    | '/portal/admin/vertraege'
    | '/portal/auftraege/$id'
    | '/portal/auftraege/neu'
    | '/portal/feld/woche'
    | '/portal/kunden/$id'
    | '/portal/postfach/$id'
    | '/portal/postfach/neu'
    | '/portal/auftraege'
    | '/portal/feld'
    | '/portal/kunden'
    | '/portal/postfach'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/app'
    | '/beratung'
    | '/datenschutz'
    | '/energie'
    | '/impressum'
    | '/karriere'
    | '/kunde'
    | '/login'
    | '/portal'
    | '/ueber-uns'
    | '/vorschau'
    | '/app/karte'
    | '/app/liste'
    | '/app/mehr'
    | '/app/suche'
    | '/portal/benachrichtigungen'
    | '/portal/planung'
    | '/portal/profil'
    | '/portal/provisionen'
    | '/portal/steuern'
    | '/portal/team'
    | '/portal/wissen'
    | '/app/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/docusign/connect'
    | '/portal/admin/audit'
    | '/portal/admin/benutzer'
    | '/portal/admin/einstellungen'
    | '/portal/admin/gebiete'
    | '/portal/admin/leads'
    | '/portal/admin/mail'
    | '/portal/admin/onboarding'
    | '/portal/admin/partner'
    | '/portal/admin/produkte'
    | '/portal/admin/qualitaet'
    | '/portal/admin/regionen'
    | '/portal/admin/reports'
    | '/portal/admin/signatur'
    | '/portal/admin/vertraege'
    | '/portal/auftraege/$id'
    | '/portal/auftraege/neu'
    | '/portal/feld/woche'
    | '/portal/kunden/$id'
    | '/portal/postfach/$id'
    | '/portal/postfach/neu'
    | '/portal/auftraege/'
    | '/portal/feld/'
    | '/portal/kunden/'
    | '/portal/postfach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  AppRoute: typeof AppRouteWithChildren
  BeratungRoute: typeof BeratungRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EnergieRoute: typeof EnergieRoute
  ImpressumRoute: typeof ImpressumRoute
  KarriereRoute: typeof KarriereRoute
  KundeRoute: typeof KundeRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  UeberUnsRoute: typeof UeberUnsRoute
  VorschauRoute: typeof VorschauRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocusignConnectRoute: typeof ApiDocusignConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beratung': {
      id: '/beratung'
      path: '/beratung'
      fullPath: '/beratung'
      preLoaderRoute: typeof BeratungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energie': {
      id: '/energie'
      path: '/energie'
      fullPath: '/energie'
      preLoaderRoute: typeof EnergieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunde': {
      id: '/kunde'
      path: '/kunde'
      fullPath: '/kunde'
      preLoaderRoute: typeof KundeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vorschau': {
      id: '/vorschau'
      path: '/vorschau'
      fullPath: '/vorschau'
      preLoaderRoute: typeof VorschauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/karte': {
      id: '/app/karte'
      path: '/karte'
      fullPath: '/app/karte'
      preLoaderRoute: typeof AppKarteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/liste': {
      id: '/app/liste'
      path: '/liste'
      fullPath: '/app/liste'
      preLoaderRoute: typeof AppListeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mehr': {
      id: '/app/mehr'
      path: '/mehr'
      fullPath: '/app/mehr'
      preLoaderRoute: typeof AppMehrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suche': {
      id: '/app/suche'
      path: '/suche'
      fullPath: '/app/suche'
      preLoaderRoute: typeof AppSucheRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/benachrichtigungen': {
      id: '/portal/benachrichtigungen'
      path: '/benachrichtigungen'
      fullPath: '/portal/benachrichtigungen'
      preLoaderRoute: typeof PortalBenachrichtigungenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/planung': {
      id: '/portal/planung'
      path: '/planung'
      fullPath: '/portal/planung'
      preLoaderRoute: typeof PortalPlanungRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profil': {
      id: '/portal/profil'
      path: '/profil'
      fullPath: '/portal/profil'
      preLoaderRoute: typeof PortalProfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/provisionen': {
      id: '/portal/provisionen'
      path: '/provisionen'
      fullPath: '/portal/provisionen'
      preLoaderRoute: typeof PortalProvisionenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/steuern': {
      id: '/portal/steuern'
      path: '/steuern'
      fullPath: '/portal/steuern'
      preLoaderRoute: typeof PortalSteuernRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/team': {
      id: '/portal/team'
      path: '/team'
      fullPath: '/portal/team'
      preLoaderRoute: typeof PortalTeamRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/wissen': {
      id: '/portal/wissen'
      path: '/wissen'
      fullPath: '/portal/wissen'
      preLoaderRoute: typeof PortalWissenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docusign/connect': {
      id: '/api/docusign/connect'
      path: '/api/docusign/connect'
      fullPath: '/api/docusign/connect'
      preLoaderRoute: typeof ApiDocusignConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin/audit': {
      id: '/portal/admin/audit'
      path: '/admin/audit'
      fullPath: '/portal/admin/audit'
      preLoaderRoute: typeof PortalAdminAuditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/benutzer': {
      id: '/portal/admin/benutzer'
      path: '/admin/benutzer'
      fullPath: '/portal/admin/benutzer'
      preLoaderRoute: typeof PortalAdminBenutzerRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/einstellungen': {
      id: '/portal/admin/einstellungen'
      path: '/admin/einstellungen'
      fullPath: '/portal/admin/einstellungen'
      preLoaderRoute: typeof PortalAdminEinstellungenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/gebiete': {
      id: '/portal/admin/gebiete'
      path: '/admin/gebiete'
      fullPath: '/portal/admin/gebiete'
      preLoaderRoute: typeof PortalAdminGebieteRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/leads': {
      id: '/portal/admin/leads'
      path: '/admin/leads'
      fullPath: '/portal/admin/leads'
      preLoaderRoute: typeof PortalAdminLeadsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/mail': {
      id: '/portal/admin/mail'
      path: '/admin/mail'
      fullPath: '/portal/admin/mail'
      preLoaderRoute: typeof PortalAdminMailRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/onboarding': {
      id: '/portal/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/portal/admin/onboarding'
      preLoaderRoute: typeof PortalAdminOnboardingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/partner': {
      id: '/portal/admin/partner'
      path: '/admin/partner'
      fullPath: '/portal/admin/partner'
      preLoaderRoute: typeof PortalAdminPartnerRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/produkte': {
      id: '/portal/admin/produkte'
      path: '/admin/produkte'
      fullPath: '/portal/admin/produkte'
      preLoaderRoute: typeof PortalAdminProdukteRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/qualitaet': {
      id: '/portal/admin/qualitaet'
      path: '/admin/qualitaet'
      fullPath: '/portal/admin/qualitaet'
      preLoaderRoute: typeof PortalAdminQualitaetRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/regionen': {
      id: '/portal/admin/regionen'
      path: '/admin/regionen'
      fullPath: '/portal/admin/regionen'
      preLoaderRoute: typeof PortalAdminRegionenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/reports': {
      id: '/portal/admin/reports'
      path: '/admin/reports'
      fullPath: '/portal/admin/reports'
      preLoaderRoute: typeof PortalAdminReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/signatur': {
      id: '/portal/admin/signatur'
      path: '/admin/signatur'
      fullPath: '/portal/admin/signatur'
      preLoaderRoute: typeof PortalAdminSignaturRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin/vertraege': {
      id: '/portal/admin/vertraege'
      path: '/admin/vertraege'
      fullPath: '/portal/admin/vertraege'
      preLoaderRoute: typeof PortalAdminVertraegeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/auftraege/': {
      id: '/portal/auftraege/'
      path: '/auftraege'
      fullPath: '/portal/auftraege/'
      preLoaderRoute: typeof PortalAuftraegeIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/auftraege/$id': {
      id: '/portal/auftraege/$id'
      path: '/auftraege/$id'
      fullPath: '/portal/auftraege/$id'
      preLoaderRoute: typeof PortalAuftraegeIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/auftraege/neu': {
      id: '/portal/auftraege/neu'
      path: '/auftraege/neu'
      fullPath: '/portal/auftraege/neu'
      preLoaderRoute: typeof PortalAuftraegeNeuRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/feld/': {
      id: '/portal/feld/'
      path: '/feld'
      fullPath: '/portal/feld/'
      preLoaderRoute: typeof PortalFeldIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/feld/woche': {
      id: '/portal/feld/woche'
      path: '/feld/woche'
      fullPath: '/portal/feld/woche'
      preLoaderRoute: typeof PortalFeldWocheRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/kunden/': {
      id: '/portal/kunden/'
      path: '/kunden'
      fullPath: '/portal/kunden/'
      preLoaderRoute: typeof PortalKundenIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/kunden/$id': {
      id: '/portal/kunden/$id'
      path: '/kunden/$id'
      fullPath: '/portal/kunden/$id'
      preLoaderRoute: typeof PortalKundenIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/postfach/': {
      id: '/portal/postfach/'
      path: '/postfach'
      fullPath: '/portal/postfach/'
      preLoaderRoute: typeof PortalPostfachIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/postfach/$id': {
      id: '/portal/postfach/$id'
      path: '/postfach/$id'
      fullPath: '/portal/postfach/$id'
      preLoaderRoute: typeof PortalPostfachIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/postfach/neu': {
      id: '/portal/postfach/neu'
      path: '/postfach/neu'
      fullPath: '/portal/postfach/neu'
      preLoaderRoute: typeof PortalPostfachNeuRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AppRouteChildren {
  AppKarteRoute: typeof AppKarteRoute
  AppListeRoute: typeof AppListeRoute
  AppMehrRoute: typeof AppMehrRoute
  AppSucheRoute: typeof AppSucheRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKarteRoute: AppKarteRoute,
  AppListeRoute: AppListeRoute,
  AppMehrRoute: AppMehrRoute,
  AppSucheRoute: AppSucheRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalBenachrichtigungenRoute: typeof PortalBenachrichtigungenRoute
  PortalPlanungRoute: typeof PortalPlanungRoute
  PortalProfilRoute: typeof PortalProfilRoute
  PortalProvisionenRoute: typeof PortalProvisionenRoute
  PortalSteuernRoute: typeof PortalSteuernRoute
  PortalTeamRoute: typeof PortalTeamRoute
  PortalWissenRoute: typeof PortalWissenRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAdminAuditRoute: typeof PortalAdminAuditRoute
  PortalAdminBenutzerRoute: typeof PortalAdminBenutzerRoute
  PortalAdminEinstellungenRoute: typeof PortalAdminEinstellungenRoute
  PortalAdminGebieteRoute: typeof PortalAdminGebieteRoute
  PortalAdminLeadsRoute: typeof PortalAdminLeadsRoute
  PortalAdminMailRoute: typeof PortalAdminMailRoute
  PortalAdminOnboardingRoute: typeof PortalAdminOnboardingRoute
  PortalAdminPartnerRoute: typeof PortalAdminPartnerRoute
  PortalAdminProdukteRoute: typeof PortalAdminProdukteRoute
  PortalAdminQualitaetRoute: typeof PortalAdminQualitaetRoute
  PortalAdminRegionenRoute: typeof PortalAdminRegionenRoute
  PortalAdminReportsRoute: typeof PortalAdminReportsRoute
  PortalAdminSignaturRoute: typeof PortalAdminSignaturRoute
  PortalAdminVertraegeRoute: typeof PortalAdminVertraegeRoute
  PortalAuftraegeIdRoute: typeof PortalAuftraegeIdRoute
  PortalAuftraegeNeuRoute: typeof PortalAuftraegeNeuRoute
  PortalFeldWocheRoute: typeof PortalFeldWocheRoute
  PortalKundenIdRoute: typeof PortalKundenIdRoute
  PortalPostfachIdRoute: typeof PortalPostfachIdRoute
  PortalPostfachNeuRoute: typeof PortalPostfachNeuRoute
  PortalAuftraegeIndexRoute: typeof PortalAuftraegeIndexRoute
  PortalFeldIndexRoute: typeof PortalFeldIndexRoute
  PortalKundenIndexRoute: typeof PortalKundenIndexRoute
  PortalPostfachIndexRoute: typeof PortalPostfachIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBenachrichtigungenRoute: PortalBenachrichtigungenRoute,
  PortalPlanungRoute: PortalPlanungRoute,
  PortalProfilRoute: PortalProfilRoute,
  PortalProvisionenRoute: PortalProvisionenRoute,
  PortalSteuernRoute: PortalSteuernRoute,
  PortalTeamRoute: PortalTeamRoute,
  PortalWissenRoute: PortalWissenRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalAdminAuditRoute: PortalAdminAuditRoute,
  PortalAdminBenutzerRoute: PortalAdminBenutzerRoute,
  PortalAdminEinstellungenRoute: PortalAdminEinstellungenRoute,
  PortalAdminGebieteRoute: PortalAdminGebieteRoute,
  PortalAdminLeadsRoute: PortalAdminLeadsRoute,
  PortalAdminMailRoute: PortalAdminMailRoute,
  PortalAdminOnboardingRoute: PortalAdminOnboardingRoute,
  PortalAdminPartnerRoute: PortalAdminPartnerRoute,
  PortalAdminProdukteRoute: PortalAdminProdukteRoute,
  PortalAdminQualitaetRoute: PortalAdminQualitaetRoute,
  PortalAdminRegionenRoute: PortalAdminRegionenRoute,
  PortalAdminReportsRoute: PortalAdminReportsRoute,
  PortalAdminSignaturRoute: PortalAdminSignaturRoute,
  PortalAdminVertraegeRoute: PortalAdminVertraegeRoute,
  PortalAuftraegeIdRoute: PortalAuftraegeIdRoute,
  PortalAuftraegeNeuRoute: PortalAuftraegeNeuRoute,
  PortalFeldWocheRoute: PortalFeldWocheRoute,
  PortalKundenIdRoute: PortalKundenIdRoute,
  PortalPostfachIdRoute: PortalPostfachIdRoute,
  PortalPostfachNeuRoute: PortalPostfachNeuRoute,
  PortalAuftraegeIndexRoute: PortalAuftraegeIndexRoute,
  PortalFeldIndexRoute: PortalFeldIndexRoute,
  PortalKundenIndexRoute: PortalKundenIndexRoute,
  PortalPostfachIndexRoute: PortalPostfachIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  AppRoute: AppRouteWithChildren,
  BeratungRoute: BeratungRoute,
  DatenschutzRoute: DatenschutzRoute,
  EnergieRoute: EnergieRoute,
  ImpressumRoute: ImpressumRoute,
  KarriereRoute: KarriereRoute,
  KundeRoute: KundeRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  UeberUnsRoute: UeberUnsRoute,
  VorschauRoute: VorschauRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocusignConnectRoute: ApiDocusignConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
